#! /bin/sh

me=$(basename $0)
mydir=$(dirname $0)

package="$1"
destdir="$2"

if [ -z "$package" ] ; then
  echo "Usage: $me package[_oc00[.zip]] [destdir]"
  echo
  echo "This will install the include and lib dir of package[_oc00[.zip]]"
  echo "to the include and lib dir of of destdir."
  echo "If destdir is omitted, destdir will be i686-pc-os2-emx of" \
       "the parent dir of"
  echo "the dir where $me is. That is, dir/../i686-pc-os2-emx."
  exit 1
fi

# assume we're in /opt/os2emx/bin directory
prefix=$mydir/..
target=i686-pc-os2-emx
targetprefix=${destdir:-"$prefix/$target"}

: ${WGET:=wget}
: ${UNZIP:=unzip}
: ${MKDIR_P:=mkdir -p}
: ${CP:=cp}
: ${RM:=rm}

zipurl="https://rpm.netlabs.org/release/00/zip"

# normalize package
package=${package%.zip}
package=${package%_oc00}
package="${package}_oc00.zip"

$WGET "$zipurl/$package" &&
$UNZIP -u "$package" -d "$package.dir" &&
$MKDIR_P "$targetprefix" &&
$CP -a "$package.dir/@unixroot/usr/include" "$targetprefix" &&
$CP -a "$package.dir/@unixroot/usr/lib" "$targetprefix"
$RM -rf "$package.dir" "$package"
